"""Protocol constants and error codes for SOCP (v1.1)"""

# --- Envelopes
T_USER_LIST_REQ = "USER_LIST_REQ"
T_USER_LIST     = "USER_LIST"
T_PEER_HELLO_LINK = "PEER_HELLO_LINK"
T_USER_HELLO = "USER_HELLO"
T_USER_ADVERTISE = "USER_ADVERTISE"
T_USER_REMOVE = "USER_REMOVE"
T_MSG_PRIVATE = "MSG_PRIVATE"
T_PEER_DELIVER = "PEER_DELIVER"
T_USER_DELIVER = "USER_DELIVER"
T_HEARTBEAT = "HEARTBEAT"
T_ERROR = "ERROR"

# --- DB-RPC (server<->server) and user proxies
T_DB_GET_USER = "DB_GET_USER"
T_DB_USER = "DB_USER"
T_USER_DB_GET = "USER_DB_GET_USER" # user->server request
T_USER_DB_USER = "USER_DB_USER" # server->user reply
T_DB_REGISTER = "DB_REGISTER_USER"

# --- Groups
T_GROUP_KEY_SHARE = "GROUP_KEY_SHARE"
T_MSG_GROUP       = "MSG_GROUP"

# --- Files
T_FILE_START = "FILE_START"
T_FILE_CHUNK = "FILE_CHUNK"
T_FILE_END   = "FILE_END"

# --- Error codes
E_USER_NOT_FOUND = "USER_NOT_FOUND"
E_INVALID_SIG = "INVALID_SIG"
E_BAD_KEY = "BAD_KEY"
E_TIMEOUT = "TIMEOUT"
E_UNKNOWN_TYPE = "UNKNOWN_TYPE"
E_NAME_IN_USE = "NAME_IN_USE"
